version: '2'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    -  /zfs-tank/elasticsearch:/usr/share/elasticsearch/data
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

  cerebro:
    image: yannart/cerebro:latest
    depends_on:
    - es
    ports:
    - "9001:9000"
    links:
    - es:elasticsearch
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

  kibana:
    depends_on:
    - es
    image: docker.elastic.co/kibana/kibana-oss:7.4.0
    links:
    - es:elasticsearch
    environment:
    - server.name=dcache-lab004.desy.de
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

  nginx:
    depends_on:
    - kibana
    image: dweomer/nginx-auth-ldap
    restart: always
    links:
    - kibana:kibana
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

    volumes:
    - ./etc/ssl:/etc/nginx/ssl
    - ./etc/conf.d/nginx.conf:/nginx.conf
    - ./etc/conf.d/service.conf:/etc/nginx/conf.d/service.conf
    - ./etc/conf.d/ldap.conf:/etc/nginx/conf.d/ldap.conf

    ports:
    - "80:80"
    - "443:443"
